// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnica.DGII.Data;

#nullable disable

namespace PruebaTecnica.DGII.Data.Migrations
{
    [DbContext(typeof(PruebaTecnicaContext))]
    [Migration("20250824064139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PruebaTecnica.DGII.Models.ComprobanteFiscal", b =>
                {
                    b.Property<string>("NCF")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NCF");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("PruebaTecnica.DGII.Models.Contribuyente", b =>
                {
                    b.Property<string>("RncCedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RncCedula");

                    b.ToTable("Contribuyentes");
                });
#pragma warning restore 612, 618
        }
    }
}
